on:
  workflow_dispatch:

name: Manual Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Install Dependencies"
        run: yarn

      - name: "Run build"
        run: yarn build

      - name: "Publish to NPM"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          npx lerna bootstrap

          npx lerna version --conventional-commits --conventional-graduate --yes
          yarn run publish
