name: Pull Request

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  label:
    name: Set Labels
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3.0.0

      - name: "Package labels"
        uses: donmahallem/lerna-label@v0.1.15
        with:
          github_secret: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Conventional labels"
        uses: bcoe/conventional-release-labels@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
