on:
  release:
    types: [published]

name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.0.0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Install Dependencies"
        run: yarn

      - name: "Run build"
        run: yarn build

      - name: "Publish to NPM"
        run: |
          npx lerna version --conventional-commits --conventional-graduate --yes
          yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
